export const FETCH_ALL_CALLS = "FETCH_ALL_CALLS";
export const FETCH_CALLS_LOADINGS = "FETCH_CALLS_LOADINGS";
export const FETCH_CALLS_ERROR = "FETCH_CALLS_ERROR";

export const ARCHIVE_CALL = "ARCHIVE_CALL";
export const ARCHIVE_ALL_CALLS = "ARCHIVE_ALL_CALLS";
export const RESET_CALL = "RESET_CALL";
export const RESET_ALL_CALLS = "RESET_ALL_CALLS";
